// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/activity_interface.proto

#ifndef PROTOBUF_INCLUDED_proto_2factivity_5finterface_2eproto
#define PROTOBUF_INCLUDED_proto_2factivity_5finterface_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_proto_2factivity_5finterface_2eproto 

namespace protobuf_proto_2factivity_5finterface_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_proto_2factivity_5finterface_2eproto
namespace Esp8266Alert {
class AlertThresholdCross;
class AlertThresholdCrossDefaultTypeInternal;
extern AlertThresholdCrossDefaultTypeInternal _AlertThresholdCross_default_instance_;
}  // namespace Esp8266Alert
namespace google {
namespace protobuf {
template<> ::Esp8266Alert::AlertThresholdCross* Arena::CreateMaybeMessage<::Esp8266Alert::AlertThresholdCross>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Esp8266Alert {

// ===================================================================

class AlertThresholdCross : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Esp8266Alert.AlertThresholdCross) */ {
 public:
  AlertThresholdCross();
  virtual ~AlertThresholdCross();

  AlertThresholdCross(const AlertThresholdCross& from);

  inline AlertThresholdCross& operator=(const AlertThresholdCross& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AlertThresholdCross(AlertThresholdCross&& from) noexcept
    : AlertThresholdCross() {
    *this = ::std::move(from);
  }

  inline AlertThresholdCross& operator=(AlertThresholdCross&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AlertThresholdCross& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AlertThresholdCross* internal_default_instance() {
    return reinterpret_cast<const AlertThresholdCross*>(
               &_AlertThresholdCross_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AlertThresholdCross* other);
  friend void swap(AlertThresholdCross& a, AlertThresholdCross& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AlertThresholdCross* New() const final {
    return CreateMaybeMessage<AlertThresholdCross>(NULL);
  }

  AlertThresholdCross* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AlertThresholdCross>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AlertThresholdCross& from);
  void MergeFrom(const AlertThresholdCross& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AlertThresholdCross* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 crossed_thresh = 1;
  bool has_crossed_thresh() const;
  void clear_crossed_thresh();
  static const int kCrossedThreshFieldNumber = 1;
  ::google::protobuf::int64 crossed_thresh() const;
  void set_crossed_thresh(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Esp8266Alert.AlertThresholdCross)
 private:
  void set_has_crossed_thresh();
  void clear_has_crossed_thresh();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int64 crossed_thresh_;
  friend struct ::protobuf_proto_2factivity_5finterface_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AlertThresholdCross

// required int64 crossed_thresh = 1;
inline bool AlertThresholdCross::has_crossed_thresh() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AlertThresholdCross::set_has_crossed_thresh() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AlertThresholdCross::clear_has_crossed_thresh() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AlertThresholdCross::clear_crossed_thresh() {
  crossed_thresh_ = GOOGLE_LONGLONG(0);
  clear_has_crossed_thresh();
}
inline ::google::protobuf::int64 AlertThresholdCross::crossed_thresh() const {
  // @@protoc_insertion_point(field_get:Esp8266Alert.AlertThresholdCross.crossed_thresh)
  return crossed_thresh_;
}
inline void AlertThresholdCross::set_crossed_thresh(::google::protobuf::int64 value) {
  set_has_crossed_thresh();
  crossed_thresh_ = value;
  // @@protoc_insertion_point(field_set:Esp8266Alert.AlertThresholdCross.crossed_thresh)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Esp8266Alert

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_proto_2factivity_5finterface_2eproto
