// Code generated by protoc-gen-go. DO NOT EDIT.
// source: activity_interface.proto

package Esp8266Alert

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlertThresholdCross struct {
	CrossedThresh        *int64   `protobuf:"varint,1,req,name=crossed_thresh,json=crossedThresh" json:"crossed_thresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlertThresholdCross) Reset()         { *m = AlertThresholdCross{} }
func (m *AlertThresholdCross) String() string { return proto.CompactTextString(m) }
func (*AlertThresholdCross) ProtoMessage()    {}
func (*AlertThresholdCross) Descriptor() ([]byte, []int) {
	return fileDescriptor_222d4acf42810e0e, []int{0}
}

func (m *AlertThresholdCross) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlertThresholdCross.Unmarshal(m, b)
}
func (m *AlertThresholdCross) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlertThresholdCross.Marshal(b, m, deterministic)
}
func (m *AlertThresholdCross) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlertThresholdCross.Merge(m, src)
}
func (m *AlertThresholdCross) XXX_Size() int {
	return xxx_messageInfo_AlertThresholdCross.Size(m)
}
func (m *AlertThresholdCross) XXX_DiscardUnknown() {
	xxx_messageInfo_AlertThresholdCross.DiscardUnknown(m)
}

var xxx_messageInfo_AlertThresholdCross proto.InternalMessageInfo

func (m *AlertThresholdCross) GetCrossedThresh() int64 {
	if m != nil && m.CrossedThresh != nil {
		return *m.CrossedThresh
	}
	return 0
}

func init() {
	proto.RegisterType((*AlertThresholdCross)(nil), "Esp8266Alert.AlertThresholdCross")
}

func init() { proto.RegisterFile("activity_interface.proto", fileDescriptor_222d4acf42810e0e) }

var fileDescriptor_222d4acf42810e0e = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4c, 0x2e, 0xc9,
	0x2c, 0xcb, 0x2c, 0xa9, 0x8c, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x71, 0x2d, 0x2e, 0xb0, 0x30, 0x32, 0x33, 0x73, 0xcc, 0x49,
	0x2d, 0x2a, 0x51, 0xb2, 0xe1, 0x12, 0x06, 0x33, 0x42, 0x32, 0x8a, 0x52, 0x8b, 0x33, 0xf2, 0x73,
	0x52, 0x9c, 0x8b, 0xf2, 0x8b, 0x8b, 0x85, 0x54, 0xb9, 0xf8, 0x92, 0x41, 0x8c, 0xd4, 0x94, 0xf8,
	0x12, 0xb0, 0x8c, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x73, 0x10, 0x2f, 0x54, 0x14, 0xa2, 0x1c, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xcf, 0x8f, 0xfa, 0x92, 0x66, 0x00, 0x00, 0x00,
}
